---
#
# Disables EPEL repositories
#

- hosts: cloud
  remote_user: root
  tasks:
    - name: Disable EPEL repositories
      ini_file:
        dest: "/etc/yum.repos.d/{{ item }}.repo"
        section: "{{ item }}"
        option: enabled
        value: "0"
      with_items:
        - epel
        - epel-modular
        - epel-playground
        - epel-testing
        - epel-testing-modular
      when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"
      tags:
        - rhosp
        - never

