---
#
# Steps required to be carried out as the stack user to deploy the overcloud
#

- hosts: undercloud
  remote_user: stack
  tasks:
    - name: Copy over the undercloud-passwords.conf file
      copy:
        src: /home/stack/builddir/undercloud-passwords.conf
        dest: /home/stack/
        remote_src: yes

    - name: Extract director images
      shell: 'for i in /usr/share/rhosp-director-images/*-latest-16.0.tar; do tar -C /home/stack/images -xvf "$i"; done'

    - name: Upload images for overcloud
      shell: source /home/stack/stackrc && openstack overcloud image upload --image-path /home/stack/images

    - name: List uploaded images
      shell: source /home/stack/stackrc && openstack image list -f yaml
      register: image_list

    - debug: var=image_list.stdout_lines

    - name: List introspection PXE images
      shell: ls -l /var/lib/ironic/httpboot
      register: pxe_image_list

    - debug: var=pxe_image_list.stdout_lines

    - name: List container images
      shell: source /home/stack/stackrc && openstack tripleo container image list -f yaml
      register: container_image_list

    - debug: var=container_image_list.stdout_lines

    - name: Validate instackenv.json
      shell: source /home/stack/stackrc && openstack overcloud node import --validate-only /home/stack/instackenv.json

    - name: Import instackenv.json
      shell: source /home/stack/stackrc && openstack overcloud node import /home/stack/instackenv.json

    - name: List imported baremetal nodes
      shell: source /home/stack/stackrc && openstack baremetal node list -f yaml
      register: node_list

    - debug: var=node_list.stdout_lines

    - name: Introspect nodes
      shell: source /home/stack/stackrc && openstack overcloud node introspect --all-manageable --provide

    - name: List introspected baremetal nodes
      shell: source /home/stack/stackrc && openstack baremetal node list -f yaml
      register: introspected_node_list

    - debug: var=introspected_node_list.stdout_lines

    - name: Set root device for the nodes to boot from
      shell: source /home/stack/stackrc && /home/stack/extract_serial_for_sda.rb
      register: disk_setup_output

    - debug: var=disk_setup_output.stdout_lines

