---
#
# Installs the necessary packages for deploying RHOSP + Ceph
#

- hosts: undercloud
  remote_user: root
  tasks:
    - name: Install python3-tripleoclient
      dnf:
        name: python3-tripleoclient
        state: latest
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"
      tags:
        - rhosp
        - never

    - name: Install ceph-ansible
      dnf:
        name: ceph-ansible
        state: latest
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"
      tags:
        - rhcs
        - never

