---
#
# Creates the stack user and copies over undercloud configuration
#

- hosts: undercloud
  remote_user: root
  tasks:
    - name: Stack user on the undercloude node
      block:
        - name: Create the stack user
          user:
            name: stack

        - name: Add sudoers file for the stack user
          copy:
            src: files/sudoers_stack
            dest: /etc/sudoers.d/stack
            mode: '0440'
            owner: root
            group: root

        - name: Create ansible directories for the stack user
          file:
            path: "/home/stack/{{ item }}"
            state: directory
            owner: stack
            group: stack
          with_items:
            - images
            - templates
            - builddir

        - name: Copy a default configured undercloud.conf
          copy:
            src: files/undercloud.conf
            dest: "/home/stack/"
            owner: stack
            group: stack

        - name: Copy default registry configuration, EDIT MANUALLY
          # TODO: template it out and fill in the RHN username/password?
          copy:
            src: files/containers-prepare-parameter.yaml
            dest: "/home/stack/"
            owner: stack
            group: stack

        - name: Copy custom undercloud parameters file
          copy:
            src: files/custom-undercloud-parameter.yaml
            dest: "/home/stack/templates/"
            owner: stack
            group: stack

        - name: Copy over the script to gather disk serial numbers for overcloud nodes
          copy:
            src: files/extract_serial_for_sda.rb
            dest: "/home/stack"
            mode: '0750'
            owner: stack
            group: stack
      tags:
        - rhosp
        - never

