---
# Configures ceph client on the admin node post installation.

- hosts: "{{ groups['ceph_nodes']|first }}"
  remote_user: cephansible
  tasks:
    - name: Fetch ceph configuration and admin keyring
      become: yes
      become_user: root
      fetch:
        src: "/etc/ceph/{{ item }}"
        dest: "files/{{ item }}"
        flat: true
      with_items:
        - ceph.conf
        - ceph.client.admin.keyring

- hosts: ceph_ansible
  remote_user: root
  tasks:
    - name: Install the copied ceph configuration files system-wide
      copy:
        src: "files/{{ item }}"
        dest: "/etc/ceph/{{ item }}"
        owner: root
        group: root
      with_items:
        - ceph.conf
        - ceph.client.admin.keyring

    - name: Set permissions on ceph.client.admin.keyring
      file:
        path: "/etc/ceph/ceph.client.admin.keyring"
        mode: '0400'

    - name: Get ceph cluster status
      command: ceph -s
      register: ceph_status
      changed_when: false
      run_once: true

    - name: Show ceph status
      debug:
        msg: "{{ ceph_status.stdout_lines }}"
      run_once: true
