---
# Installs ceph-ansible packages and configures the inventory.
# If the custom-dns tag is used, also configures DNS resolution for the cluster

- hosts: ceph_all
  remote_user: root
  tasks:
    - name: Install chrony config file for RH lab network
      copy:
        src: files/chrony.conf
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: '0644'

    - name: Restart chronyd
      systemd:
        name: chronyd
        state: restarted

- hosts: ceph_nodes
  remote_user: root
  tasks:
    - name: Unmask firewalld on ceph nodes and reload daemons
      systemd:
        name: firewalld
        masked: no
        daemon_reload: yes

- hosts: ceph_ansible
  remote_user: root
  tasks:
    - name: dnf install ceph-ansible
      dnf:
        name:
          - ceph-ansible
          - ceph-common
        state: present
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"

    - name: yum install ceph-ansible
      yum:
        name:
          - ceph-ansible
          - ceph-common
        state: present
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"

    - name: Populate hosts inventory for ceph-ansible
      template:
        src: templates/ceph-ansible/hosts.j2
        dest: /etc/ansible/hosts
        owner: root
        group: root
        mode: '0644'

    - name: Populate all.yml for ceph-ansible
      template:
        src: templates/ceph-ansible/group_vars/all.yml.j2
        dest: /usr/share/ceph-ansible/group_vars/all.yml
        owner: root
        group: root
        mode: '0644'

    - name: Copy osds.yml for ceph-ansible
      copy:
        src: templates/ceph-ansible/group_vars/osds.yml
        dest: /usr/share/ceph-ansible/group_vars/osds.yml
        owner: root
        group: root
        mode: '0644'

    - name: Copy site-docker.yml on the host for ceph-ansible
      copy:
        src: /usr/share/ceph-ansible/site-container.yml.sample
        dest: /usr/share/ceph-ansible/site-container.yml
        owner: root
        group: root
        mode: '0644'
        remote_src: yes

    - name: Create ceph-ansible-keys directory
      become: yes
      become_user: cephansible
      file:
        path: /home/cephansible/ceph-ansible-keys
        state: directory

- name: Custom DNS configuration for the ceph cluster
  hosts: ceph_all
  tasks:
    - name: dnf install dnsmasq
      dnf:
        name:
          - dnsmasq
        state: present
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"

    - name: yum install dnsmasq
      yum:
        name:
          - dnsmasq
        state: present
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"

    - name: Debug hosts file render
      debug:
        msg: "{{ lookup('template', 'templates/hosts_ceph.j2') }}"

    - name: Install hosts file
      template:
        src: templates/hosts_ceph.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: '644'

    - name: Ensure NetworkManager configuration directories exist
      file:
        path: "/etc/NetworkManager/{{ item }}"
        state: directory
      with_items:
        - conf.d
        - dnsmasq.d

    - name: Debug dnsmasq file render
      debug:
        msg: "{{ lookup('template', 'templates/NetworkManager/dnsmasq.d/ceph.conf.j2') }}"

    - name: Install NetworkManager dnsmasq configuration
      template:
        src: templates/NetworkManager/dnsmasq.d/ceph.conf.j2
        dest: /etc/NetworkManager/dnsmasq.d/ceph.conf
        owner: root
        group: root
        mode: '644'

    - name: Debug NetworkManager file render
      debug:
        msg: "{{ lookup('template', 'templates/NetworkManager/conf.d/00-use-dnsmasq.conf.j2') }}"

    - name: Configure NetworkManager to use dnsmasq
      template:
        src: templates/NetworkManager/conf.d/00-use-dnsmasq.conf.j2
        dest: /etc/NetworkManager/conf.d/00-use-dnsmasq.conf
        owner: root
        group: root
        mode: '644'

    - name: Manage the system interface using NetworkManager to allow DNS changes
      lineinfile:
        path: "/etc/sysconfig/network-scripts/ifcfg-{{ hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['interface'] }}"
        regexp: '^NM_CONTROLLED='
        line: NM_CONTROLLED=yes

    - name: Reload NetworkManager
      systemd:
        name: NetworkManager
        state: restarted

    - name: Check FQDN DNS resolution
      command: "host -t A {{ item }}.cephcluster"
      with_inventory_hostnames:
        - ceph_nodes

    - name: Check FQDN DNS resolution connectivity
      command: "ping -c1 {{ item }}.cephcluster"
      with_inventory_hostnames:
        - ceph_nodes

    - name: Check hostname-only DNS resolution connectivity
      command: "ping -c1 {{ item }}"
      with_inventory_hostnames:
        - ceph_nodes
  tags:
    - custom-dns
    - never

- name: Custom DNS hostname setup
  hosts: ceph_nodes
  tasks:
    - name: Change hostname on the cluster nodes
      hostname:
        name: "{{ inventory_hostname }}.cephcluster"
  tags:
    - custom-dns
    - never
