---
# Sets up the ceph ansible user and distributes its ssh key to all the
# other hosts to allow ceph-ansible based deployment.

- hosts: ceph_all
  remote_user: root
  tasks:
    - name: cephansible user creation on all ceph nodes
      block:
        - name: Create cephansible user
          user:
            name: cephansible

        - name: Add sudoers file for the cephansible user
          copy:
            src: files/sudoers_cephansible
            dest: /etc/sudoers.d/sudoers_cephansible
            mode: '0440'
            owner: root
            group: root

- hosts: ceph_ansible
  remote_user: cephansible
  tasks:
    - name: cephansible user ssh key creation
      block:
        - name: Create ssh key for cephansible user
          shell: "ssh-keygen -t rsa -N '' -C 'cephansible' -f ~/.ssh/id_rsa"
          args:
            executable: /bin/bash
            creates: /home/cephansible/.ssh/id_rsa

        - name: Fetch cephansible user's ssh public key
          fetch:
            src: /home/cephansible/.ssh/id_rsa.pub
            dest: files/ssh_keys/cephansible.pub
            flat: true

- hosts: ceph_ansible
  remote_user: root
  tasks:
    - name: root user ssh key creation
      block:
        - name: Create ssh key for cephansible user
          shell: "ssh-keygen -t rsa -N '' -C 'root@cephansible' -f ~/.ssh/id_rsa"
          args:
            executable: /bin/bash
            creates: /root/.ssh/id_rsa

        - name: Fetch root user's ssh public key
          fetch:
            src: /root/.ssh/id_rsa.pub
            dest: files/ssh_keys/root.pub
            flat: true

- hosts: ceph_all
  remote_user: root
  tasks:
    - name: Distribution of the cephansible users' ssh key to all ceph nodes
      authorized_key:
        user: cephansible
        state: present
        key: "{{ item }}"
        with_file:
          - files/ssh_keys/cephansible.pub
          - files/ssh_keys/root.pub

    - name: Distribution of additional users' ssh keys to all ceph nodes
      authorized_key:
        user: cephansible
        state: present
        key: "{{ item }}"
        with_files: "{{ ssh_pub_key_files }}"

- hosts: ceph_ansible
  remote_user: cephansible
  tasks:
    - name: Verify sudo access over ssh on other ceph hosts
      shell: "ssh -q -o BatchMode=yes -o StrictHostKeyChecking=no {{ item }} 'sudo hostname && exit'"
      delegate_to: "{{ inventory_hostname }}"
      with_items:
        - "{{ groups['ceph_all'] }}"

