---
#
# Disables EPEL repositories
#

- hosts: ceph_all
  remote_user: root
  tasks:
    - name: Disable EPEL repositories
      block:
        - name: Disable EPEL repositories on RHEL 8
          ini_file:
            dest: "/etc/yum.repos.d/{{ item }}.repo"
            section: "{{ item }}"
            option: enabled
            value: "0"
          with_items:
            - epel
            - epel-modular
            - epel-playground
            - epel-testing
            - epel-testing-modular
          when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"

        - name: Disable EPEL repositories on RHEL 7
          ini_file:
            dest: "/etc/yum.repos.d/{{ item }}.repo"
            section: "{{ item }}"
            option: enabled
            value: "0"
          with_items:
            - epel
            - epel-testing
          when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"
      tags:
        - rhcs
        - never

