---
#
# Enables the subscription manager repositories
#

- hosts: ceph_all
  remote_user: root
  tasks:
  - name: RHSM registration.
    block:
      - name: Fail if RHSM user is not provided.
        fail:
          msg: "rhsm_user must be defined if registration is enabled."
        when: ( rhsm_user is not defined ) or ( rhsm_user == None) or ( rhsm_user|length == 0 )

      - name: Fail if RHSM password is not provided.
        fail:
          msg: "rhsm_password must be defined if registration is enabled."
        when: ( rhsm_password is not defined ) or ( rhsm_password == None) or ( rhsm_password|length == 0 )

      - name: RHSM registration on RHEL 8.
        block:
          - name: Register via subscription-manager.
            redhat_subscription:
              state: present
              username: "{{ rhsm_user }}"
              password: "{{ rhsm_password }}"
              pool_ids: "{{ pool_id_rhel_8 | default(omit) }}"
              consumer_id: "{{ hostvars[inventory_hostname]['rhsm_consumer_id'] | default(omit) }}"
        when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"

      - name: RHSM registration on RHEL 7.
        block:
          - name: Register via subscription-manager.
            redhat_subscription:
              state: present
              username: "{{ rhsm_user }}"
              password: "{{ rhsm_password }}"
              pool_ids: "{{ pool_id_rhel_7 | default(omit) }}"
              consumer_id: "{{ hostvars[inventory_hostname]['rhsm_consumer_id'] | default(omit) }}"
        when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"
    tags: rhsm-registration

  - name: RHSM repositories.
    block:
      - name: RHSM repositories on RHEL 8.
        block:
          - name: Disable all RHSM repositories
            rhsm_repository:
              name: '*'
              state: disabled

          - name: Enable base RHEL repositories on all hosts.
            rhsm_repository:
              name:
                - rhel-8-for-x86_64-baseos-rpms
                - rhel-8-for-x86_64-appstream-rpms
              state: enabled
        when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"

      - name: RHSM repositories on RHEL 7.
        block:
          - name: Disable all RHSM repositories.
            rhsm_repository:
              name: '*'
              state: disabled

          - name: Enable base RHEL repositories on all hosts.
            rhsm_repository:
              name:
                - rhel-7-server-rpms
                - rhel-7-server-extras-rpms
              state: enabled
        when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"

- hosts: ceph_ansible
  remote_user: root
  tasks:
  - name: Enable ceph repository on ansible node
    block:
      - name: Enable ceph repository on RHEL 8
        rhsm_repository:
          name:
            - rhceph-4-tools-for-rhel-8-x86_64-rpms
            - ansible-2.8-for-rhel-8-x86_64-rpms
          state: enabled
        when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"

      - name: Enable ceph repository on RHEL 7
        rhsm_repository:
          name:
            - rhel-7-server-rhceph-4-tools-rpms
            - rhel-7-server-ansible-2.8-rpms
          state: enabled
        when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"
